[package]
name = "trash"
version = "0.1.0"
authors = ["Warren Galyen"]
edition = "2018"
license = "MIT"
license-file = "LICENSE"

[dependencies]

[target.'cfg(windows)'.dependencies]
winapi = { version = "^0.3.0", features = ["shellapi", "winerror"] } 